### ISSUE TITLE
Add window opacity control

### ISSUE THREAD

**Issue by douglaslassance** [curzel-it/pipper#8]
Maybe this isn't possible, it would be a nice to have.

**Comment by curzel-it** [comment]
It actually is possible!
I have another app that works by showing a transparent window on top of the whole screen: [Desktop Pets for macOS](https://github.com/curzel-it/bit-therapy)

There's some caveats:
1. Can't control alpha of title bars
2. Hiding the title bar completely makes the window not resizable (can still add custom code to resize, but, you know...)

This basically boils down to: Yes, we can, just need a custom toolbar!

There's another user request about making the title bar/tool bar go away unless you over or something to make it cleaner, so it's something that I eventually need to do.

It's tricky because as I mentioned there's a bunch of things that come for free with a tool bar (window resing for example), but the system then would become much more flexible.
Another cool thing we can do going down that route is allowing users to place the toolbar on other sides of the window for example, or just make the list customizable and gg.

I'll think about it!

**Comment by curzel-it** [comment]
![image](https://github.com/curzel-it/pipper/assets/1446790/fb172e5e-8ada-4f93-a5b3-634e3fdbedf9)
Next week!

**Comment by curzel-it** [comment]
Released in v1.4!
